.Dd $Mdocdate$
.Dt RAIDCAT 1
.Os
.Sh NAME
.Nm raidcat
.Nd does stuff
.Sh SYNOPSIS
.Nm 
.Op Fl t devtype
.Ar path
.Sh DESCRIPTION
.Nm
Parses raidcat data...?
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl t
Set the device type. The default is...
.Sh EXIT STATUS
.Nm
exits with good exit codes
.Sh EXAMPLES
Check an intel raid device...
.Bd -literal -width indent
$ raidcat -t intel
.Sh SEE ALSO
.Xr icinga2 1
